In [ ]:
'''
1. Create a null vector of size 10 but the fifth value which is 1.
2. Create a vector with values ranging from 10 to 49.
3. Create a 3x3 matrix with values ranging from 0 to 8
4. Find indices of non-zero elements from [1,2,0,0,4,0]
5. Create a 10x10 array with random values and find the minimum and maximum values.
6. Create a random vector of size 30 and find the mean value.
'''

In [9]:
'''1. Create a null vector of size 10 but the fifth value which is 1.'''
import numpy as np
a=np.zeros(10,dtype=int)
a[4]=1
print(a)

[0 0 0 0 1 0 0 0 0 0]


In [10]:
'''2. Create a vector with values ranging from 10 to 49.'''
b=np.arange(10,50,dtype=int)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
'''3. Create a 3x3 matrix with values ranging from 0 to 8'''
b=np.arange(9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [31]:
'''4. Find indices of non-zero elements from [1,2,0,0,4,0]'''
a=np.array([1,2,0,0,4,0])
b=np.array(np.nonzero(a))
print('The index of all non zero element of array is {}'.format(b))

The index of all non zero element of array is [[0 1 4]]


In [29]:
'''5. Create a 10x10 array with random values and find the minimum and maximum values.'''
a=np.random.randint(low=10,high=1000,size=(10,10))
print(a)
print('The maximum number in the array is {}'.format(a.max()))
print('The minimum number in the array is {}'.format(a.min()))

[[759 320 861 816 195 831 613 443 232 159]
 [353 744 391 122 776 310 418 551 758 585]
 [655 830 542 857 538 648 849 435 102 411]
 [516 429 332 826 645 854 860 377 102 541]
 [149 194 780 536 226  89  71 195 323 654]
 [ 30 741 327 701 540 533 324 184  23 321]
 [667 876 495 714 489  14 184 374 874 349]
 [561 978 976 129 695 190 176 902  96 672]
 [578 342 444 819 603 747 984 153 867 417]
 [897 422 924 770 236 282 770 959 494 423]]
The maximum number in the array is 984
The minimum number in the array is 14


In [32]:
'''6. Create a random vector of size 30 and find the mean value.'''
a=np.random.randint(low=10,high=1000,size=(30,))
print(a)
print('The mean value of the give array is {}'.format(a.mean()))

[247  52 551 428  33 916 766 643  11 367 557 485 897 468 603 517 364 451
 751 330 303 225  83  99 238 851 176 932 933 928]
The mean value of the give array is 473.5
